// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectOrganizer.Api.Data;

#nullable disable

namespace ProjectOrganizer.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401175236_AddKlijentPotvrdioToCheckListItems")]
    partial class AddKlijentPotvrdioToCheckListItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectOrganizer.Api.Models.AiReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AktivnostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RemindAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AktivnostId");

                    b.HasIndex("ProjekatId");

                    b.HasIndex("UserId");

                    b.HasIndex("RemindAt", "Sent");

                    b.ToTable("AiReminders", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Aktivnost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Bau")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalji")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectImplementationItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vrsta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectImplementationItemId");

                    b.HasIndex("ProjekatId");

                    b.HasIndex("Status");

                    b.ToTable("Aktivnosti", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.CheckListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Kompleksnost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CheckListItems", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Codebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("EntityTypeId", "Code")
                        .IsUnique();

                    b.HasIndex("EntityTypeId", "IsActive");

                    b.ToTable("Codebooks", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.CodebookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CodebookEntities", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.DailyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("KorisnikKreirao")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Pinned")
                        .HasColumnType("bit");

                    b.Property<bool>("Solved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikKreirao");

                    b.HasIndex("KorisnikKreirao", "Datum");

                    b.ToTable("DailyTasks", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.DevOpsTasksCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptanceCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AktivnostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estimation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AktivnostId");

                    b.HasIndex("UserId");

                    b.ToTable("DevOpsTasksCandidates");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.DocumentNumbering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DocumentNumbering");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Dokument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazivFajla")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<string>("TipFajla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Velicina")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjekatId");

                    b.ToTable("Dokumenti");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ImplementationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalji")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ImplementationModelId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ImplementationModelId");

                    b.ToTable("ImplementationItems", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ImplementationItemCheckListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckListItemId")
                        .HasColumnType("int");

                    b.Property<int>("ImplementationItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckListItemId");

                    b.HasIndex("ImplementationItemId");

                    b.ToTable("ImplementationItemCheckListItems", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ImplementationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("Aktivan");

                    b.ToTable("ImplementationModels", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Klijent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaticniBroj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PdvRegistrationDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PdvStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pib")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zemlja")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Naziv");

                    b.ToTable("Klijenti", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjekatId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AktivnostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AktivnostId");

                    b.HasIndex("ProjekatId");

                    b.HasIndex("ReferenceKey")
                        .HasFilter("[ReferenceKey] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ProjectImplementationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImplementationItemId")
                        .HasColumnType("int");

                    b.Property<int>("ImplementationModelId")
                        .HasColumnType("int");

                    b.Property<bool>("KlijentPotvrdio")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KlijentPotvrdioDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Napomena")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("Zavrseno")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ZavrsenoDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImplementationItemId");

                    b.HasIndex("ImplementationModelId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectImplementationItems", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ProjectImplementationItemCheckList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckListItemId")
                        .HasColumnType("int");

                    b.Property<bool>("KlijentPotvrdio")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KlijentPotvrdioDatum")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Procenat")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProjectImplementationItemId")
                        .HasColumnType("int");

                    b.Property<bool>("Zavrsen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ZavrsenDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CheckListItemId");

                    b.HasIndex("ProjectImplementationItemId");

                    b.ToTable("ProjectImplementationItemCheckLists", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ProjectPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjekatId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectPermissions");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Projekat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AIPracen")
                        .HasColumnType("bit");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("BrojProjekta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("DevOpsAreaPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DevOpsIterationPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DevOpsOrganization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DevOpsProject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GoogleSheetId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ImplementationModelId")
                        .HasColumnType("int");

                    b.Property<int>("KlijentId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrojProjekta")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ImplementationModelId");

                    b.HasIndex("KlijentId");

                    b.HasIndex("Status");

                    b.ToTable("Projekti", (string)null);
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DevOpsPersonalAccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OpenAiApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OpenAiModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.AiReminder", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.Aktivnost", "Aktivnost")
                        .WithMany()
                        .HasForeignKey("AktivnostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjectOrganizer.Api.Models.Projekat", "Projekat")
                        .WithMany()
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectOrganizer.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Aktivnost");

                    b.Navigation("Projekat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Aktivnost", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("ProjectOrganizer.Api.Models.ProjectImplementationItem", "ProjectImplementationItem")
                        .WithMany()
                        .HasForeignKey("ProjectImplementationItemId");

                    b.HasOne("ProjectOrganizer.Api.Models.Projekat", "Projekat")
                        .WithMany("Aktivnosti")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CreatedByUser");

                    b.Navigation("ProjectImplementationItem");

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Codebook", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.CodebookEntity", "EntityType")
                        .WithMany("Codebooks")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.DailyTask", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("KorisnikKreirao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.DevOpsTasksCandidate", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.Aktivnost", "Aktivnost")
                        .WithMany()
                        .HasForeignKey("AktivnostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectOrganizer.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktivnost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Dokument", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.Projekat", "Projekat")
                        .WithMany()
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ImplementationItem", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.ImplementationModel", "ImplementationModel")
                        .WithMany("Items")
                        .HasForeignKey("ImplementationModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImplementationModel");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ImplementationItemCheckListItem", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.CheckListItem", "CheckListItem")
                        .WithMany()
                        .HasForeignKey("CheckListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectOrganizer.Api.Models.ImplementationItem", "ImplementationItem")
                        .WithMany("CheckListItems")
                        .HasForeignKey("ImplementationItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckListItem");

                    b.Navigation("ImplementationItem");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Note", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.Projekat", "Projekat")
                        .WithMany()
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Notification", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.Aktivnost", "Aktivnost")
                        .WithMany()
                        .HasForeignKey("AktivnostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProjectOrganizer.Api.Models.Projekat", "Projekat")
                        .WithMany()
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectOrganizer.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktivnost");

                    b.Navigation("Projekat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ProjectImplementationItem", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.ImplementationItem", "ImplementationItem")
                        .WithMany()
                        .HasForeignKey("ImplementationItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectOrganizer.Api.Models.ImplementationModel", "ImplementationModel")
                        .WithMany()
                        .HasForeignKey("ImplementationModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectOrganizer.Api.Models.Projekat", "Project")
                        .WithMany("ImplementationItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImplementationItem");

                    b.Navigation("ImplementationModel");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ProjectImplementationItemCheckList", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.CheckListItem", "CheckListItem")
                        .WithMany()
                        .HasForeignKey("CheckListItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectOrganizer.Api.Models.ProjectImplementationItem", "ProjectImplementationItem")
                        .WithMany("CheckLists")
                        .HasForeignKey("ProjectImplementationItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckListItem");

                    b.Navigation("ProjectImplementationItem");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ProjectPermission", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.Projekat", "Projekat")
                        .WithMany()
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectOrganizer.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Projekat", b =>
                {
                    b.HasOne("ProjectOrganizer.Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectOrganizer.Api.Models.ImplementationModel", "ImplementationModel")
                        .WithMany()
                        .HasForeignKey("ImplementationModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectOrganizer.Api.Models.Klijent", "Klijent")
                        .WithMany("Projekti")
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ImplementationModel");

                    b.Navigation("Klijent");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.CodebookEntity", b =>
                {
                    b.Navigation("Codebooks");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ImplementationItem", b =>
                {
                    b.Navigation("CheckListItems");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ImplementationModel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Klijent", b =>
                {
                    b.Navigation("Projekti");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.ProjectImplementationItem", b =>
                {
                    b.Navigation("CheckLists");
                });

            modelBuilder.Entity("ProjectOrganizer.Api.Models.Projekat", b =>
                {
                    b.Navigation("Aktivnosti");

                    b.Navigation("ImplementationItems");
                });
#pragma warning restore 612, 618
        }
    }
}
